services:
  db:
    ports:
      - "127.0.0.1:5442:5432"

  pgbouncer:
    ports:
      - "127.0.0.1:6442:5432"

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Authentication__RequireSecureCookie=false
      - RateLimiting__Global__PermitLimit=50000
      - RateLimiting__Auth__PermitLimit=50000
    ports:
      - "127.0.0.1:5010:80"

  redis:
    ports:
      - "127.0.0.1:6389:6379"

  route-optimizer:
    ports:
      - "127.0.0.1:8019:8000"

  frontend:
    ports:
      - "127.0.0.1:4211:80"

  nginx-proxy:
    ports:
      - "8088:80"

  delivery-app:
    build:
      args:
        ENABLE_MOCK_GPS: "true"
    ports:
      - "127.0.0.1:8093:80"

  osrm:
    ports:
      - "127.0.0.1:5011:5000"


  seq:
    ports:
      - "127.0.0.1:5351:5341"
      - "127.0.0.1:8092:80"

  prometheus:
    ports:
      - "127.0.0.1:9100:9090"

  grafana:
    ports:
      - "127.0.0.1:3010:3000"

  alertmanager:
    ports:
      - "127.0.0.1:9103:9093"

  rabbitmq:
    ports:
      - "127.0.0.1:5682:5672"
      - "127.0.0.1:15682:15672"

  vault:
    ports:
      - "127.0.0.1:8210:8200"

