import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:logger/logger.dart';

import '../api/services/notifications_api_service.dart';
import '../auth/auth_service.dart';

final _logger = Logger(printer: PrettyPrinter(methodCount: 0));

final pushNotificationServiceProvider = Provider<PushNotificationService>((ref) {
  return PushNotificationService(ref);
});

/// Push Notification Service
///
/// Firebase FCM requires native SDK setup (google-services.json / GoogleService-Info.plist)
/// and firebase_options.dart generated by `flutterfire configure`.
///
/// For the web Docker build we use a simulated FCM token so the backend
/// still gets a device registration (auth_provider.dart already handles this).
/// Real FCM on native mobile can be added once Firebase project is configured.
class PushNotificationService {
  final Ref _ref;
  bool _initialized = false;

  PushNotificationService(this._ref);

  /// Initialises notification service.
  /// On Web/Docker: no-op (token is registered separately in AuthNotifier.login).
  /// On native: stub — replace with real FCM when firebase_options.dart is available.
  Future<void> initialize() async {
    if (_initialized) return;
    _initialized = true;

    if (kIsWeb) {
      _logger.i('PushNotificationService: Web platform — FCM handled via simulated token in AuthNotifier');
      return;
    }

    // Native mobile: listen to auth state and register a placeholder token.
    // TODO: replace with real FirebaseMessaging.instance.getToken() once
    //       flutterfire configure has been run and firebase_options.dart exists.
    _ref.listen<AuthStatus>(authServiceProvider, (previous, next) {
      if (next == AuthStatus.authenticated) {
        _registerSimulatedToken();
      }
    }, fireImmediately: true);
  }

  Future<void> _registerSimulatedToken() async {
    try {
      final userData = await _ref.read(authServiceProvider.notifier).getUserData();
      final userId = userData?['Id'] ?? userData?['id'] ?? 'unknown';
      final token = 'sim-token-rider-$userId';

      final apiService = _ref.read(notificationsApiServiceProvider);
      await apiService.registerFcmToken(
        token: token,
        deviceType: 'ANDROID',
      );
      _logger.i('Simulated FCM token registered: ${token.substring(0, 20)}...');
    } catch (e) {
      _logger.w('Failed to register simulated FCM token (non-critical): $e');
    }
  }
}
